runtime: nodejs8
env: standard
instance_class: F1
service: default
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /scripts
    static_dir: www/scripts
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
